### ISSUE TITLE
Numeric.S.of_cstruct_be reads beyond bit_bound of max_int

### ISSUE THREAD

**Issue by cfcs** [mirleft/ocaml-nocrypto#128]
Which makes it possible to do interesting things like:
```
utop # Nocrypto.Numeric.Int32.of_cstruct_be ~bits:43 Cstruct.(of_string "\x00\x00\x00\x00\x01\x80");;
- : int32 = 12l
```

Maybe it's just me being weird, but I would expect it to read up to 32 bits (for `Int32`) instead of overflowing.
```
utop # Nocrypto.Numeric.Int32.bit_bound Int32.max_int;;
- : int = 32
```

The builtin int types have silent overflow, of course, so that turns out to work just fine, but if I wanted to make a `Nocrypto.Numeric.S` module for use with `Nocrypto.Rng.Make_N` that used an "overflow-safe" type module that threw exceptions on overflow, this would not fare well (contrived example for the time being).

**Comment by pqwy** [comment]
Believe it or not, this is actually intended. In fact I rely on it somewhere, but I can't recall where, using it to effectively shift the start of reading.

It is probably surprising, for sure. I haven't gotten around to documenting these and I sort-of think of that as an internal utility. Do you have use for these functions outside?

If you created your own type, I assume you would base it off of one of the existing representations, so you would probably have an injection from the ground type. In which case the easiest way to read them would be to read the ground type and inject it, so your result would exactly match the existing behavior without triggering errors.

Am I missing something here?

**Comment by cfcs** [comment]
I think the functionality could be useful, but would prefer it to be strict about the number of bits considered, with an `?offset` parameter (which would make it even more useful; less bit masking in application code).

In the present state where the functionality is not documented it *feels* like an internal function, potentially subject to change, so I would be reluctant to depend on it.

**Comment by pqwy** [comment]
This is the correct choice -- do not depend on it.

As an alternative, never ask it to decode more bits than the type you are decoding contains. That part of functionality is robust.

**Comment by cfcs** [comment]
Shouldn't it be explained in the `.mli` that an exposed type is to be considered !exposed and for internal use only?

**Comment by pqwy** [comment]
Oh but you can freely use it, as long as you don't go ahead and ask it to overflow. As I said, that part of the functionality is pretty robust.

**Comment by cfcs** [comment]
Oh well, different standards for software quality I guess.

**Comment by pqwy** [comment]
Be sure to leave links to a couple of your projects so I can learn.

**Comment by pqwy** [comment]
Ok, it dawned on me that if I leave this amused banter, someone might read it and conclude that this issue has merit.

Consider a sequence of leaves, potentially of infinite length, but with a defined beginning. Imagine there are frogs sitting on some of the leaves. Now consider the problem: how do you create a sequence of length `k` by copying the first `n` leaves?

Strictly, this makes sense only if `k` and `n` are the same. But you decide that you like your functions total wherever reasonable.

You have `F _ F _ _ F F ...` and the `k` is 4. Then the problematic `n` is either greater or smaller.

Suppose that `n` is smaller, say 2. How do you make a 4-sequence using just `F _`? Well if there were alternating frogs and groundhogs there would be no clear answer. But if the states are not symmetric, if there is an "empty leaf" situation, you can just start with 4 empty leaves and pull the sequence in from the right. So the answers are `_ _ _ _ |`, `_ _ _ | F`, `_ _ | F _` and `_ | F _ F`.

Neat. You really needed that. But what if `n` is larger, maybe 5? You can imagine just continuing the process of pulling the sequence to the left under the 4-wide window until the `k`-the position shows up. You see`F [_ F _ _] F F`, the result being `_ F _ _`.

So you can say that you generalized the operation of *picking the first `n` positions* to the operation of *picking the last `k` of the first `n` positions*, `n` being the parameter and `k` being the baked-in window size. The cool bit is that this behaves uniformly even if `k` is infinite.

What you are doing here is slicing bit-strings, and the overflow only exists in the numeric interpretation of one of the several ways to lose information.

So unless there is a different, simpler generalization of the first-k operation, that uniformly covers `n < k`, `n > k` and an infinite `k`, I don't believe there even *is* an issue here. I always thought that `of_cstruct_be` was doing the only possible thing.

**Comment by cfcs** [comment]
You seem to miss the point entirely, which is not a claim that your code is flawed, but the fact that in order to rely on it I have to open "issues" on github.com to ask how it is intended to work, and whether or not I can rely on its undocumented behavior not to change. Then wait for somewhere between 14 days to 8 months (or forever), and ask follow-up questions, bearing with some smug, passively aggressive remarks, until I receive the information I could just have read in the interface documentation:
> Believe it or not, this is actually intended. In fact I rely on it somewhere, but I can't recall where, using it to effectively shift the start of reading.
> It is probably surprising, for sure. I haven't gotten around to documenting these and I sort-of think of that as an internal utility.

We are not at war. If you don't want people who do not fall into the category of misunderstood geniuses to use your library, or the undocumented functions, or just plain don't want to have listen to them at all, that's cool, but it saves everyone time if you tell them, or just document it in the README (though in the latter case it would be considered more polite to notify them in private).
Same goes for preferred point of contact, or preferred way for new features to be implemented.

**Comment by pqwy** [comment]
[Documented](https://github.com/mirleft/ocaml-nocrypto/commit/f5ee0bc15399795048977511c2664ebcfc48a6b8), can be relied upon.

If you need a quicker response shoot an email. I don't have your private contact. You'll get one of my "Misunderstood Genius" caps if you divulge that.

Thanks for reporting!
