### ISSUE TITLE
Incompatible with cstruct 3.4.0

### ISSUE THREAD

**Issue by copy** [mirleft/ocaml-nocrypto#155]
See https://github.com/ocaml/opam-repository/pull/13372/commits/3c554d25536b512213fa6a437f875e57159cc57e

**Comment by XVilka** [comment]
There is a new Cstruct version - [3.7.0](https://github.com/mirage/ocaml-cstruct/releases/tag/v3.7.0)

**Comment by copy** [comment]
This has been fixed in https://github.com/ocaml/opam-repository/commit/47ad7a5211b174d80253beb78cd7d8163531bca3.
