### ISSUE TITLE
DH woes

### ISSUE THREAD

**Issue by pqwy** [mirleft/ocaml-nocrypto#20]
DH has a number of edge-cases, which we need to be secured against.

Some references are [Anderson and Vaudenay](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.56.1921) and [Raymond and Stiglic](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.21.639).

**Comment by hannesm** [comment]
I think this can be closed now, or?

**Comment by pqwy** [comment]
Calling this done.
