### ISSUE TITLE
cstruct equality

### ISSUE THREAD

**Issue by hannesm** [mirleft/ocaml-nocrypto#47]
with `cstruct-1.5.0` installed, and using crunch to save and restore X509 certificates, I cannot get `X509.Cert.of_pem_cstruct` to return any useful certificate (this is on mirage-unix, same file works great on lwt-unix).

A solution is to add to the `Cs.equal` (in `ocaml-x509/lib/x509`) the `~mask:true` argument - which uses then not bigarray, but a slower equality here in nocrypto. Might also be solved by https://github.com/mirage/ocaml-cstruct/pull/45

But having `equal` resulting in different results, depending on whether `~mask` is given or not, is very confusing.

**Comment by hannesm** [comment]
tested https://github.com/mirage/ocaml-cstruct/pull/45 - which solves the issue for me. can we please have that merged in cstruct and released @avsm @samoht?

**Comment by pqwy** [comment]
Although I'm more than eager to have https://github.com/mirage/ocaml-cstruct/pull/45 as soon as possible, I would value a minimal test case here. I personally never had a breakage, running the exact same code on both `mirage-xen/x86_64` and `mirage-unix/x86_64` machines, and running other code that calls this, on `lwt-unix/x86_64`. N.B. I always ran it on Linux, whereas you are running it on FreeBSD.

The current comparison with `~mask:false` hands off to `Cstruct.to_bigarray`, which quickly ends up being `Array1.sub` (`caml_ba_sub`), followed by polymorphic comparison for bigarrays, `caml_ba_compare`, both in `otherlibs/bigarray/bigarray_stubs.c` in the compiler source tree.

So if this breaks for you, it smells like parts of standard OCaml stubs, or what's below them, fail on case of mirage-on-unix-on-FreeBSD. This should be investigated.

**Comment by hannesm** [comment]
this fails only when using `crunch` on FreeBSD - not when using `direct_kv_ro` (fs-unix)... still investigating, but something also requires io-page-1.2.0 on my system (which might be related to this failure)...

**Comment by hannesm** [comment]
https://github.com/hannesm/test is a testcase for this bug -- the assertion in line 24 fails here on FreeBSD (code is mainly copied from the stuff `ocaml-crunch` generated)

**Comment by pqwy** [comment]
That's interesting. It runs without problems on my system. `glibc.2.20` from my distro, `io-page.1.4.0`.

**Comment by pqwy** [comment]
It doesn't die here with `io-page.1.2.0` either.

**Comment by hannesm** [comment]
https://github.com/hannesm/test dies here also with `io-page-1.4.0` -- @avsm @talex5 any idea?

**Comment by hannesm** [comment]
actually independent of nocrypto...
