### ISSUE TITLE
Get rid of `lwt.syntax`?

### ISSUE THREAD

**Issue by samoht** [mirleft/ocaml-nocrypto#59]
Not sure why you are using it exactly, but would be better to not depend on `camlp4` as it will be deprecated at one point in the near future.

**Comment by pqwy** [comment]
True. Is there a way to update a release or should I just do `0.4.1`?

**Comment by pqwy** [comment]
Btw. I removed the dep on `lwt.syntax`. I actually like that extra syntax, but as it was a small file, it probably wasn't worthwhile dragging that dep.

But the core still depends on `camlp4` via `sexplib.syntax`. Not sure how go about avoiding that one...

**Comment by samoht** [comment]
It's fine if you delete and recreate the tag I think.

**Comment by pqwy** [comment]
Yup, re-did the release. Now without `lwt.syntax`.

But it still depends on `camlp4`.
