### ISSUE TITLE
nocrypto-0.5.0 fails on Mac OS X 10.10.4

### ISSUE THREAD

**Issue by schoeke** [mirleft/ocaml-nocrypto#75]
```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of nocrypto failed at "./configure --prefix
        /Users/XXXXXXXXX/.opam/system --enable-lwt --disable-xen".
Processing  1/6: [nocrypto: ocamlfind remove]
=== ERROR while installing nocrypto.0.5.0 ====================================#
 opam-version 1.2.2
 os           darwin
 command      ./configure --prefix /Users/XXXXXXXXX/.opam/system --enable-lwt --disable-xen
 path         /Users/XXXXXXXXX/.opam/system/build/nocrypto.0.5.0
 compiler     system (4.02.1)
 exit-code    1
 env-file     /Users/XXXXXXXX/.opam/system/build/nocrypto.0.5.0/nocrypto-22386-e4db2f.env
 stdout-file  /Users/XXXXXXXX/.opam/system/build/nocrypto.0.5.0/nocrypto-22386-e4db2f.out
 stderr-file  /Users/XXXXXXXX/.opam/system/build/nocrypto.0.5.0/nocrypto-22386-e4db2f.err
 stderr
 src/native/cpudetect_static.c:20:14: error: use of undeclared identifier 'signature_INTEL_ebx'
   if (sig == signature_INTEL_ebx || sig == signature_AMD_ebx) {
              ^
 src/native/cpudetect_static.c:20:44: error: use of undeclared identifier 'signature_AMD_ebx'
   if (sig == signature_INTEL_ebx || sig == signature_AMD_ebx) {
                                            ^
 2 errors generated.
 E: Failure("Command './postconf' terminated with error code 1")
```

Occurs with the following setup:
➜  ~  gcc --version        
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix

Mac OS X Yosemite 10.10.4 (14E46) with XCode Version 6.4 (6E35b). 

Please let me know if you need more information.

**Comment by hannesm** [comment]
[this is actually nocrypto-master taken via https://github.com/hannesm/xmpp-opam/blob/master/packages/nocrypto/nocrypto.0.5.0/url]

**Comment by pqwy** [comment]
This happens if the C compiler is too old and its `cpuid.h` lacks definitions for `signature_INTEL_ebx` and `signature_AMD_ebx`, the constants CPU emits to self-identify the brand.

I am a little confused by the version output, it looks like the command asked `gcc` for the version but this looks like `clang`'s output? What is your `$(which cc)`? My hunch is that an older `gcc` was used here.

This was tested on `clang-3.6.1` and `gcc-4.9.0` up to `gcc-5.1.0`. If the compilers common on current macs lack these definitions, I can add them in. But if this fails, then older Mirage would already fail because [entropy](https://github.com/pqwy/mirage-entropy/blob/master/lib/entropy_cpu_xen_stubs.c) uses similar code.

**Comment by schoeke** [comment]
➜  ~  which gcc   
/usr/bin/gcc

I have been testing jackline for some time and this is the first time the error occurs. I am not quite sure how this error could come about to be honest, but I have no indication, that it uses not the version I reported here.

I have several cpuid.h files, some belonging to XCode, others to brewed programs, but nothing that should interfere here. Any idea how I could check which header files is being used? (Sorry, not a C* person.)

A quick check reveals that the definition of signature_INTEL_ebx  is not in the XCode supplied cpuid.h.

**Comment by pqwy** [comment]
> I have been testing jackline for some time and this is the first time the error occurs.

That's understandable, `nocrypto-0.5.0` (and esp. the master) is the first time CPU fiddling appeared in jackline's dep graph.

Could you please try cloning `nocrypto` and doing:

```
clang src/native/cpudetect_static.c -o /tmp/xxx.1
```
```
gcc src/native/cpudetect_static.c -o /tmp/xxx.2
```

The second one should fail, but that would indicate `gcc-4.8.0` or earlier.

Also, are you sure the above version output is from `gcc`?

**Comment by schoeke** [comment]
➜  ocaml-nocrypto git:(master) clang src/native/cpudetect_static.c -o /tmp/xxx.1
src/native/cpudetect_static.c:20:14: error: use of undeclared identifier 'signature_INTEL_ebx'
  if (sig == signature_INTEL_ebx || sig == signature_AMD_ebx) {
             ^
src/native/cpudetect_static.c:20:44: error: use of undeclared identifier 'signature_AMD_ebx'
  if (sig == signature_INTEL_ebx || sig == signature_AMD_ebx) {
                                           ^
2 errors generated.
➜  ocaml-nocrypto git:(master) gcc src/native/cpudetect_static.c -o /tmp/xxx.2
src/native/cpudetect_static.c:20:14: error: use of undeclared identifier 'signature_INTEL_ebx'
  if (sig == signature_INTEL_ebx || sig == signature_AMD_ebx) {
             ^
src/native/cpudetect_static.c:20:44: error: use of undeclared identifier 'signature_AMD_ebx'
  if (sig == signature_INTEL_ebx || sig == signature_AMD_ebx) {
                                           ^
2 errors generated.

To my knowledge, gcc is basically a clang alias under Mac OS X by now. This also explains the verion output as well.

**Comment by schoeke** [comment]
"Starting with Xcode version 5 (released with OS X 10.9 Mavericks), Apple has removed support for gcc, such that gcc is no longer actually the GNU Compiler Collection, but is symlinked to the  clang compiler."
https://support.enthought.com/hc/en-us/articles/204469410-OS-X-GCC-Clang-and-Cython-in-10-9-Mavericks

This is a problem with the headers provided by clang.

**Comment by schoeke** [comment]
Fix worked as far as I can see. jackline is happy again.

**Comment by pqwy** [comment]
This is incredibly weird. I regularly test with `clang` and the header that comes with my `3.6.1` has those constants. Apple is playing games which I know nothing about here.

8ff2fb2c0f31a9552083200779451bd268d8ca95 works around the absence of the constants as it's just a throwaway configure-time snippet, but this gives me a bad gut feeling. I expect to keep breaking Macs as we go forward because I don't have one and I don't understand what is going on with their compilers.

**Comment by schoeke** [comment]
I am happy to help. But not knowing much about compilers on Macs myself, that might be limited.

**Comment by hannesm** [comment]
we can also setup the (brittle) travis OSX builder http://docs.travis-ci.com/user/osx-ci-environment/ (as done in opam-repository)...
