### ISSUE TITLE
nocrypto-inhibit-modernity is not a valid variable

### ISSUE THREAD

**Issue by j0sh** [mirleft/ocaml-nocrypto#77]
Getting this error when installing nocrypto.0.5.1 via OPAM:

[ERROR] nocrypto-inhibit-modernity is not a valid variable.
[WARNING] Invalid variable nocrypto-inhibit-modernity in filter
[ERROR] 'nocrypto-inhibit-modernity' has type string, but a env element of type bool was expected.
[ERROR] The compilation of nocrypto.0.5.1 failed.

Haven't done anything to set the nocrypto-inhibit-modernity var explicitly; it doesn't exist in the OPAM config here.

**Comment by pqwy** [comment]
This is weird. I can't seem to reproduce with opam 1.2.2. Which version do you have? /cc @samoht 

(For a quick fix, `opam pin add nocrypto --dev-repo && opam pin edit nocrypto` and remove the offending line.)

**Comment by j0sh** [comment]
Ah, was on opam 1.2.0. Upgraded to 1.2.2, and installing nocrypto.0.5.1 works now, thanks!

**Comment by yallop** [comment]
Is it worth adding an `opam-version >= "1.2.2"` constraint to the `opam` file?

**Comment by avsm** [comment]
This is a problem -- we have to support 1.2.0 as well...

**Comment by pqwy** [comment]
@avsm Hmm, what do we do here? Just by virtue of referring to that var, opam 1.2.0 is not supported by the current `opam` file.

**Comment by samoht** [comment]
Can you add a `post-messages` in the opam file? 

> `post-messages` (since version 1.1.0) allows to print specific messages to the user after the end of installation. The special boolean variable failure is defined in the scope of the filter, and can be used to print messages in case there was an error (typically, a hint on how it can be resolved, or a link to an open issue). success is also defined as syntactic sugar for !failure.

They are useful to help the user resolve build errors and typical workaround.
