### ISSUE TITLE
Hex

### ISSUE THREAD

**Issue by vbmithr** [mirleft/ocaml-nocrypto#80]
There is Base64, would be good to have Hex too.

**Comment by cfcs** [comment]
:+1:

There is `Uncommon.Cs.of_hex`, but a to_hex would be great too.
And I agree that hex en- and decoding is a common enough thing that perhaps it shouldn't be in `Uncommon.Cs`?

**Comment by samoht** [comment]
See https://github.com/mirage/ocaml-hex

**Comment by cfcs** [comment]
Same could be said for https://github.com/mirage/ocaml-base64 which is already reimplemented as `Nocrypto.Base64`

I am familiar with `ocaml-hex`, but I don't see the point of having to include an additional module in the trusted codebase just to be able to hex-encode strings when there is a precedence for Base64 encoding/decoding and hex decoding.

When we will (hopefully soon!) have codesigning in opam, this means that any application that wants to use `Nocrypto` and needs to do hex-decoding will have to trust both the `Nocrypto` package AND the `ocaml-hex` package.

Like I said above, it also seems like a common thing that developers who are doing crypto would want to do. One example is showing hex fingerprints (like in `ocaml-x509`), and for serializing whatever value that Nocrypto currently needs to decode.
