### ISSUE TITLE
Aren't there any MACs in there?

### ISSUE THREAD

**Issue by UnixJunkie** [mirleft/ocaml-nocrypto#83]
Like RIPEMD160?
I did not see any in the API.
Did I miss them?

**Comment by pqwy** [comment]
Aha, [there](http://mirleft.github.io/ocaml-nocrypto/Nocrypto.Hash.S.html#VALhmac) [are](http://mirleft.github.io/ocaml-nocrypto/Nocrypto.Hash.html#VALmac).

No RIPEMD though.
