### ISSUE TITLE
openbsd build failure

### ISSUE THREAD

**Issue by avsm** [mirleft/ocaml-nocrypto#86]
```
cc1: unrecognized build option -maes
```

**Comment by hannesm** [comment]
wonder whether it should use `-march=native` (as proposed [here](https://github.com/mirleft/ocaml-nocrypto/issues/73#issuecomment-119295052)) then (or pass `-maes` only when `-DACCELERATE` is used)

**Comment by pqwy** [comment]
f9b6de192a847db0213f29ba3b0bfeb5c9940ecf is pretty robust now. I can't get it to _not_ build on OpenBSD however I twist its arm.

**Comment by pqwy** [comment]
... and ec061f004df246e3b4eec260b9e8aef02ac88038 replaces the Opam variable with an env var.

Now builds on OpenBSD with the pre-packaged `opam-1.2.0`.

**Comment by avsm** [comment]
awesome! will try shortly

**Comment by pqwy** [comment]
Ok, this seems long gone.
