### ISSUE TITLE
Cannot load nocrypto.cmxs: undefined symbols from zarith

### ISSUE THREAD

**Issue by mfp** [mirleft/ocaml-nocrypto#90]
Trying to `Dynlink.loadfile` the `nocrypto.cmxs` shared object fails with an error like

     Error loading nocrypto.cmxs: error loading shared library: /home/mfp/.opam/4.02.3+fp/lib/nocrypto/nocrypto.cmxs: undefined symbol: ml_z_of_int32

(Dynlink is of practical importance e.g. when trying to use nocrypto with the Ocsigen webserver.)

This happens even when `zarith.cmxs` is loaded before. This behavior can be reproduced trivially with this snippet:

    let () =
      for i = 1 to Array.length Sys.argv - 1 do
        try
          Dynlink.loadfile Sys.argv.(i)
        with Dynlink.Error err ->
          Printf.printf "Error loading %s: %s\n" Sys.argv.(i) (Dynlink.error_message err)
      done

    $ loaddynlib ../zarith/zarith.cmxs nocrypto.cmxs
    Error loading nocrypto.cmxs: error loading shared library: /home/mfp/.opam/4.02.3+fp/lib/nocrypto/nocrypto.cmxs: undefined symbol: ml_z_of_int32

**Comment by mfp** [comment]
Running the above under `ltrace` shows that `zarith.cmxs` is being loaded properly with the  `RTLD_GLOBAL` flag:

     dlopen("../zarith/zarith.cmxs", 4354)         = 0x00eac330

    ....
    $ grep RTLD_GLOBAL /usr/include/x86_64-linux-gnu/bits/dlfcn.h
    #define RTLD_GLOBAL	0x00100
    /* Unix98 demands the following flag which is the inverse to RTLD_GLOBAL.
    $

So it looks like something should be linking against `-lzarith` so that `dllzarith.so` (which includes the missing symbol) is loaded.

**Comment by mfp** [comment]
On further inspection, I've found that `zarith.cmxs` does not include the code corresponding to its own stub objects. If I create it with `$ ocamlopt -shared -o zarith.cmxs zarith.cmxa  -linkall -cclib -L.` the required symbols are included and it becomes possible to load `nocrypto.cmxs` (only after its dependencies are loaded, of course: zarith.cmxs, bigarray.cmxs, sexplib.cmxs, ocplib-endian/bigstring.ccmxs, cstruct.cmxs). 

`nocrypto.cmxs` (and other `cmxs` plugins) seems to be built correctly and not require `-linkall` since  the `nocrypto.cmx` pack is explicitly included (so same transitive closure algorithm used for static linking is applied).

**Comment by Yuren-Zhong** [comment]
I have encountered a similar problem. I try to `Dynlink.loadfile "graphics.cmxs"`, and then the error message is:
`Dynlink error: error loading shared library: /home/harvey/.opam/4.04.0/lib/ocaml/graphics.cmxs: undefined symbol: camlHashtbl`
Do you have any idea how to fix it ?
